//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows;


namespace LQClass.ModuleOfLog.I18nResources
{
	public static class Language
	{
		public static readonly ComponentResourceKey MainTabItemView_Header = new ComponentResourceKey(typeof(UiResource), nameof(MainTabItemView_Header));
		public static readonly ComponentResourceKey ITCode = new ComponentResourceKey(typeof(UiResource), nameof(ITCode));
		public static readonly ComponentResourceKey LogType = new ComponentResourceKey(typeof(UiResource), nameof(LogType));
		public static readonly ComponentResourceKey Normal = new ComponentResourceKey(typeof(UiResource), nameof(Normal));
		public static readonly ComponentResourceKey Exception = new ComponentResourceKey(typeof(UiResource), nameof(Exception));
		public static readonly ComponentResourceKey Debug = new ComponentResourceKey(typeof(UiResource), nameof(Debug));
		public static readonly ComponentResourceKey StartTime = new ComponentResourceKey(typeof(UiResource), nameof(StartTime));
		public static readonly ComponentResourceKey EndTime = new ComponentResourceKey(typeof(UiResource), nameof(EndTime));
		public static readonly ComponentResourceKey Search = new ComponentResourceKey(typeof(UiResource), nameof(Search));
		public static readonly ComponentResourceKey Reset = new ComponentResourceKey(typeof(UiResource), nameof(Reset));
		public static readonly ComponentResourceKey Delete = new ComponentResourceKey(typeof(UiResource), nameof(Delete));
		public static readonly ComponentResourceKey Export = new ComponentResourceKey(typeof(UiResource), nameof(Export));
		public static readonly ComponentResourceKey ModuleName = new ComponentResourceKey(typeof(UiResource), nameof(ModuleName));
		public static readonly ComponentResourceKey ActionName = new ComponentResourceKey(typeof(UiResource), nameof(ActionName));
		public static readonly ComponentResourceKey ActionTime = new ComponentResourceKey(typeof(UiResource), nameof(ActionTime));
		public static readonly ComponentResourceKey Duration = new ComponentResourceKey(typeof(UiResource), nameof(Duration));
		public static readonly ComponentResourceKey Remark = new ComponentResourceKey(typeof(UiResource), nameof(Remark));
		public static readonly ComponentResourceKey Action = new ComponentResourceKey(typeof(UiResource), nameof(Action));
		public static readonly ComponentResourceKey Add = new ComponentResourceKey(typeof(UiResource), nameof(Add));
		public static readonly ComponentResourceKey Save = new ComponentResourceKey(typeof(UiResource), nameof(Save));
		public static readonly ComponentResourceKey Cancel = new ComponentResourceKey(typeof(UiResource), nameof(Cancel));
	}
}
