//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows;


namespace LQClass.ModuleOfMenuManagement.I18nResources
{
	public static class Language
	{
		public static readonly ComponentResourceKey MainTabItemView_Header = new ComponentResourceKey(typeof(UiResource), nameof(MainTabItemView_Header));
	}
}
