//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows;


namespace LQClass.AdminForWPF.I18nResources
{
	public static class Language
	{
		public static readonly ComponentResourceKey App_Title = new ComponentResourceKey(typeof(UiResource), nameof(App_Title));
		public static readonly ComponentResourceKey LoginView_UserLblTitle = new ComponentResourceKey(typeof(UiResource), nameof(LoginView_UserLblTitle));
		public static readonly ComponentResourceKey LoginView_UserInputToolTip = new ComponentResourceKey(typeof(UiResource), nameof(LoginView_UserInputToolTip));
		public static readonly ComponentResourceKey LoginView_PasswordInputToolTip = new ComponentResourceKey(typeof(UiResource), nameof(LoginView_PasswordInputToolTip));
		public static readonly ComponentResourceKey LoginView_PasswordLblTitle = new ComponentResourceKey(typeof(UiResource), nameof(LoginView_PasswordLblTitle));
		public static readonly ComponentResourceKey LoginView_RememberMe = new ComponentResourceKey(typeof(UiResource), nameof(LoginView_RememberMe));
		public static readonly ComponentResourceKey LoginView_AutoLogin = new ComponentResourceKey(typeof(UiResource), nameof(LoginView_AutoLogin));
		public static readonly ComponentResourceKey LoginView_LoginButtonContent = new ComponentResourceKey(typeof(UiResource), nameof(LoginView_LoginButtonContent));
		public static readonly ComponentResourceKey Repository = new ComponentResourceKey(typeof(UiResource), nameof(Repository));
		public static readonly ComponentResourceKey About = new ComponentResourceKey(typeof(UiResource), nameof(About));
		public static readonly ComponentResourceKey QQGroup = new ComponentResourceKey(typeof(UiResource), nameof(QQGroup));
		public static readonly ComponentResourceKey Email = new ComponentResourceKey(typeof(UiResource), nameof(Email));
		public static readonly ComponentResourceKey OK = new ComponentResourceKey(typeof(UiResource), nameof(OK));
		public static readonly ComponentResourceKey Foreground = new ComponentResourceKey(typeof(UiResource), nameof(Foreground));
		public static readonly ComponentResourceKey Background = new ComponentResourceKey(typeof(UiResource), nameof(Background));
		public static readonly ComponentResourceKey Recommendation = new ComponentResourceKey(typeof(UiResource), nameof(Recommendation));
		public static readonly ComponentResourceKey Website = new ComponentResourceKey(typeof(UiResource), nameof(Website));
		public static readonly ComponentResourceKey Home = new ComponentResourceKey(typeof(UiResource), nameof(Home));
		public static readonly ComponentResourceKey System = new ComponentResourceKey(typeof(UiResource), nameof(System));
		public static readonly ComponentResourceKey Log = new ComponentResourceKey(typeof(UiResource), nameof(Log));
		public static readonly ComponentResourceKey User_Management = new ComponentResourceKey(typeof(UiResource), nameof(User_Management));
		public static readonly ComponentResourceKey Role_Management = new ComponentResourceKey(typeof(UiResource), nameof(Role_Management));
		public static readonly ComponentResourceKey Group_Management = new ComponentResourceKey(typeof(UiResource), nameof(Group_Management));
		public static readonly ComponentResourceKey Menu_Mangement = new ComponentResourceKey(typeof(UiResource), nameof(Menu_Mangement));
		public static readonly ComponentResourceKey Data_Privilege = new ComponentResourceKey(typeof(UiResource), nameof(Data_Privilege));
	}
}