//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LQClass.AdminForWPF.I18nResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LQClass.AdminForWPF.I18nResources.UiResource", typeof(UiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LQClass 的本地化字符串。
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background 的本地化字符串。
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Foreground 的本地化字符串。
        /// </summary>
        public static string Foreground {
            get {
                return ResourceManager.GetString("Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Log In 的本地化字符串。
        /// </summary>
        public static string LoginView_AutoLogin {
            get {
                return ResourceManager.GetString("LoginView_AutoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log in 的本地化字符串。
        /// </summary>
        public static string LoginView_LoginButtonContent {
            get {
                return ResourceManager.GetString("LoginView_LoginButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input password, the test passwrod is lqclass.com 的本地化字符串。
        /// </summary>
        public static string LoginView_PasswordInputToolTip {
            get {
                return ResourceManager.GetString("LoginView_PasswordInputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string LoginView_PasswordLblTitle {
            get {
                return ResourceManager.GetString("LoginView_PasswordLblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remember Me 的本地化字符串。
        /// </summary>
        public static string LoginView_RememberMe {
            get {
                return ResourceManager.GetString("LoginView_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input account, the test acount is lqclass.com 的本地化字符串。
        /// </summary>
        public static string LoginView_UserInputToolTip {
            get {
                return ResourceManager.GetString("LoginView_UserInputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account 的本地化字符串。
        /// </summary>
        public static string LoginView_UserLblTitle {
            get {
                return ResourceManager.GetString("LoginView_UserLblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Privilege 的本地化字符串。
        /// </summary>
        public static string MainMenu_Data_Privilege {
            get {
                return ResourceManager.GetString("MainMenu_Data_Privilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group Management 的本地化字符串。
        /// </summary>
        public static string MainMenu_Group_Management {
            get {
                return ResourceManager.GetString("MainMenu_Group_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string MainMenu_Home {
            get {
                return ResourceManager.GetString("MainMenu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        public static string MainMenu_Log {
            get {
                return ResourceManager.GetString("MainMenu_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu Mangement 的本地化字符串。
        /// </summary>
        public static string MainMenu_Menu_Mangement {
            get {
                return ResourceManager.GetString("MainMenu_Menu_Mangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role Management 的本地化字符串。
        /// </summary>
        public static string MainMenu_Role_Management {
            get {
                return ResourceManager.GetString("MainMenu_Role_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string MainMenu_System {
            get {
                return ResourceManager.GetString("MainMenu_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Management 的本地化字符串。
        /// </summary>
        public static string MainMenu_User_Management {
            get {
                return ResourceManager.GetString("MainMenu_User_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ Group 的本地化字符串。
        /// </summary>
        public static string QQGroup {
            get {
                return ResourceManager.GetString("QQGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recommendation 的本地化字符串。
        /// </summary>
        public static string Recommendation {
            get {
                return ResourceManager.GetString("Recommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository 的本地化字符串。
        /// </summary>
        public static string Repository {
            get {
                return ResourceManager.GetString("Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Website 的本地化字符串。
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
